### PR TITLE
In-chart navigation with brush container

### PR DESCRIPTION
**Pull request by jotak**
It can be seen in storybook: ChartWithLegend / "as scatter with dates and in-chart navigation"

Capture d’écran de 2020-02-06 15-56-16

It allows to zoom-in charts.

Part of https://github.com/kiali/kiali/issues/1860

### CODE REVIEW

**Comment by mtho11** [comment]
@jotak this is a great feature!

**Comment by jotak** [comment]
thanks @mtho11 !

**Comment by israel-hdez** [comment]
How do you go back (zoom out)?

**Comment by jotak** [comment]
> How do you go back (zoom out)?

At the moment, only by changing dates manually - this is not handled by the component itself.
Eventually we could consider using victory "zoom container" that allows zoom in/out with mouse wheel, but the problem is that it would conflict with page scrolling.

Or add zoom buttons similar to what we have on graph. Which also wouldn't be managed at this component level, it would be managed at the IstioMetrics / CustomMetrics level. Grafana does something similar:

Capture d’écran de 2020-02-10 09-24-35

I think as a first step we can consider zooming out is done by explicit date selection, and we follow-up with next tasks improving UX

**Comment by aljesusg** [comment]
Need a rebase, I am going to test this with the Jaeger integration but looks good @jotak  nice :)

**Comment by jotak** [comment]
@aljesusg yes I will rebase,
but for the jaeger integration we will need to do this as a pre-requisite: https://github.com/kiali/kiali/issues/2147
Because using this brush container means having custom time ranges, so it's necessary to do it as a first step.

**Comment by jotak** [comment]
rebased

**Pull request merged**
