### PR TITLE
Let any to overlay info

### PR DESCRIPTION
**Pull request by aljesusg**

### CODE REVIEW

**Comment by jotak** [comment]
I don't understand why it's needed, do you have compilation issues?

**Comment by aljesusg** [comment]
I need to add the traceID in each datapoint to link to the trace view

**Comment by jotak** [comment]
But `OverlayInfo` doesn't hold datapoints..
They are in `VCDataPoint` .. which is already `any & { ... }`:

```
export type VCDataPoint = any & {
  name: string;
  x: number | Date;
  y: number;
};
```

**Comment by aljesusg** [comment]
Mmm I saw the OverlayInfo type in the kiali-ui and this is why I sent this PR, let me check it

**Comment by aljesusg** [comment]
You're right we don't need it I thought it was overlayInfo.


export const toOverlay = (info: OverlayInfo, dps: VCDataPoint[

**Pull request closed without merging**
