### PR TITLE
Clean go mods

### PR DESCRIPTION
**Pull request by jotak**
- Use replace directive to fix issue with k8s version (see: https://github.com/kubernetes/apimachinery/issues/63)
- "go mod tidy", removing many unnecessary deps

### CODE REVIEW

**Comment by jotak** [comment]
@israel-hdez as suggested in the mention in apimachinery issue, using the replace directive allows to "fix" the version we want and won't be messed up by `go mod tidy`

**Comment by jotak** [comment]
(i haven't check yet how that goes with kiali ... should check it before merging)

**Comment by israel-hdez** [comment]
In Kiali, we probably will need to sync the k8s deps. I remember it complained when a version of a dep didn't match.
Not sure if same versions are needed or if that happens only in certain cases.

**Comment by jotak** [comment]
Finally, I changed again, removing the replace directives. It was causing issues with Kiali. I could run `mod tidy` anyway, even without those.. had to draw a pentagram and invoke some black magic. Now it works but I'm cursed for seven generations. Tested with Kiali.

**Pull request merged**
