### PR TITLE
Patternfly 4 update: now looking good

### PR DESCRIPTION
**Pull request by jotak**
Also fixed pf3 storybook with correct CSS

Note, it has no impact on Kiali yet

### CODE REVIEW

**Comment by jotak** [comment]
@israel-hdez or @aljesusg do you mind giving it a quick look?
What you can do is pull the PR and `cd web/react && yarn && yarn storybook` to have a look

**Comment by aljesusg** [comment]
Looks better with PF4 :)

I would use the same dataset for PF3 charts and PF4 charts @jotak for the storybook. Do you know that we can upload the storybook in githubpages free ? I can do it if you want.

Screenshot from 2019-06-13 10-32-07
Screenshot from 2019-06-13 10-31-58

**Comment by jotak** [comment]
@aljesusg about using the same dataset : yes i was thinking the same, while comparing the two charts

About uploading storybook, feel free to do so! :) you're welcome

**Comment by jotak** [comment]
@israel-hdez yes I agree, the title will have to move back to the top.
Also another regression compared to PF3 is the missing y-axis units. Will have to bring it back too.

**Pull request merged**
