### PR TITLE
KIALI-2522 Supply error in charts model, display in charts

### PR DESCRIPTION
**Pull request by jotak**
Screenshot:

error

Related JIRA: https://issues.jboss.org/browse/KIALI-2522

### CODE REVIEW

**Comment by jotak** [comment]
@israel-hdez I'm also bringing here the changes you made for empty metrics

**Comment by jotak** [comment]
@israel-hdez sure, i've documented a [build section](https://github.com/kiali/k-charted#build) but what is missing (and currently is a bit of a pain) is the development process. I've been using `yarn link` and (actually I don't remember what) to see the ongoing changes directly in Kiali. I should write a few words in the readme about that.

**Comment by israel-hdez** [comment]
@jotak I guess, right now, part the temporary setup in the back-end is to checkout https://github.com/kiali/kiali/pull/1033 ?
I could try and see if I can fill that section in the readme.

**Comment by jotak** [comment]
@israel-hdez yes, with also the related UI PR https://github.com/kiali/kiali-ui/pull/1144

**Pull request merged**
